spring.application.name=StockAndInvoiceTrackler

spring.datasource.url=jdbc:mysql://localhost:3306/stock_invoice_db
spring.datasource.username=root
spring.datasource.password=Riyajain@2002


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

